///////////////////////////////////////////////////////////////////////////
// Debug -- Schaltet diverse Debug-Funktionen ein oder aus

// wird derzeit nur von vitals und modifyskill benutzt

Const DEBUG_CHECKSKILL        := 1;
Const DEBUG_CHECKSKILLMESSAGE := 0;
Const DEBUG_ITEMS             := 1;
// NPCs debuggen (globales Flag) ?
Const DEBUG_NPC               := 1;
Const DEBUG_NPCWARNUNG        := 1;
Const DEBUG_RESULTS           := 0;
Const DEBUG_SKILLCONFIG       := 1;
Const DEBUG_SKILLS            := 1;
Const DEBUG_STATS             := 1;
Const DEBUG_VITALS            := 1;
