///////////////////////////////////////////////////////////////////////////////////////////
//
//   PergonStatistik Include - Fuehrt teilweise :) nuetzliche Statistik-Erfassungen durch
//
//     Author: Shinigami
//
//   Modifications:
//
///////////////////////////////////////////////////////////////////////////////////////////
//
// ToDo
//   naja, sowas wie, die groesste Labertasche ermitteln, also Woerter zaehlen :)
//
// Statistiken
//   InitStatistik        - Initialisiert dieses Modul
//
//   StatistikLogOnOff    - Statistische Analyse beim Ein-/Ausloggen
//   StatistikListener    - Statistische Analyse fuer das Listener-Script
//   StatistikLogging     - Statistische Analyse fuer das Logging-Script
//   StatistikMsg         - Statistische Analyse fuer das Msg-Script
//   StatistikSayAbove    - Statistische Analyse fuer das SayAbove-Script
//   StatistikSayAbovePvt - Statistische Analyse fuer das SayAbovePvt-Script
//   StatistikPartyFull   - Statistische Analyse fuer das Party-Script (alle Mitglieder)
//   StatistikPartyMember - Statistische Analyse fuer das Party-Script (einzelnes Mitglied)

/////////////////////
//                 //
//   Statistiken   //
//                 //
/////////////////////

/////////////////////////////////////////////////////
// InitStatistikPergon - Initialisiert dieses Modul
/////////////////////////////////////////////////////

Function InitStatistik()
  Return (0); // Hmm, noch keine Funktion...
EndFunction

/////////////////////////////////////////////////////////////////
// StatistikLogOnOff - Statistische Analyse beim Ein-/Ausloggen
/////////////////////////////////////////////////////////////////

Function StatistikLogOnOff(who, text)
  Return (0); // Hmm, noch keine Funktion...
EndFunction

//////////////////////////////////////////////////////////////////////
// StatistikListener - Statistische Analyse fuer das Listener-Script
//////////////////////////////////////////////////////////////////////

Function StatistikListener(who, ev)
  Return (0); // Hmm, noch keine Funktion...
EndFunction

////////////////////////////////////////////////////////////////////
// StatistikLogging - Statistische Analyse fuer das Logging-Script
////////////////////////////////////////////////////////////////////

Function StatistikLogging(ev)
  Return (0); // Hmm, noch keine Funktion...
EndFunction

////////////////////////////////////////////////////////////
// StatistikMsg - Statistische Analyse fuer das Msg-Script
////////////////////////////////////////////////////////////

Function StatistikMsg(who, whom, asciimessage)
  Return (0); // Hmm, noch keine Funktion...
EndFunction

//////////////////////////////////////////////////////////////////////
// StatistikSayAbove - Statistische Analyse fuer das SayAbove-Script
//////////////////////////////////////////////////////////////////////

Function StatistikSayAbove(who, what, text)
  Return (0); // Hmm, noch keine Funktion...
EndFunction

////////////////////////////////////////////////////////////////////////////
// StatistikSayAbovePvt - Statistische Analyse fuer das SayAbovePvt-Script
////////////////////////////////////////////////////////////////////////////

Function StatistikSayAbovePvt(who, what, text)
  Return (0); // Hmm, noch keine Funktion...
EndFunction

//////////////////////////////////////////////////////////////////////////////////////
// StatistikPartyFull - Statistische Analyse fuer das Party-Script (alle Mitglieder)
//////////////////////////////////////////////////////////////////////////////////////

Function StatistikPartyFull(character, members, msg)
  Return (0); // Hmm, noch keine Funktion...
EndFunction

///////////////////////////////////////////////////////////////////////////////////////////
// StatistikPartyMember - Statistische Analyse fuer das Party-Script (einzelnes Mitglied)
///////////////////////////////////////////////////////////////////////////////////////////

Function StatistikPartyMember(character, whom, msg)
  Return (0); // Hmm, noch keine Funktion...
EndFunction