///////////////////////////////////////////////////////////////////////////
// diverse URLs mal zusammengefasst

Const URL_BASE            := "removed";
Const URL_BASE_HTTPS      := "removed";
Const URL_CHAT            := "removed";
Const URL_CLIENT_RAR      := "removed";
Const URL_CLIENT_ZIP      := "removed";
Const URL_FAQ             := "removed";
Const URL_FORUM           := "removed";
Const URL_HANDBOOK        := "removed";
Const URL_HOMEPAGE        := "removed";
Const URL_HOME_SPIELER    := "removed";
Const URL_MAPS            := "removed";
Const URL_NEWCHAR_FAQ     := "removed";
Const URL_NEWCHAR_LP      := "removed";
Const URL_NEWS            := "removed";
Const URL_RULES           := "removed";
Const URL_RULES_NAME      := "removed";
Const URL_TREFFEN         := "removed";
Const URL_UPDATE          := "removed";
Const URL_VOTE            := "removed";
Const URL_WIKIPEDIA_POKER := "removed";
Const URL_WIKI_PERGON     := "removed";

// vim: nowrap
