function send_attack(ttarget, source, spellid := 0)
  ttarget:=ttarget;
  source:=source;
  spellid:=spellid;
//   Var ev := struct;
//   ev.+type;
//   ev.+source;
// 
//   ev.type := 0x0002;
//   ev.source := source;
//   //Spamen die NPCs zu und ueberfluten Event Queues
//   //Derzeit arbeitet keine KI damit
//   
//   //SendEvent(ttarget, ev);
//
//   if (spellid)
//      ev.+spell;
//      ev.type := 0x0800; 		//spell attack
//      ev.spell := spellid;
//      //sendevent(ttarget, ev);
//   endif

endfunction
