#!/bin/bash

LANG=C;   export LANG
LC_ALL=C; export LC_ALL
cvs log -N -d "${1:->= today -1 day}" |
    awk '
        BEGIN { show = 0 }
        /^RCS file:/ {
            gsub(/^RCS file: \/pergon\/Pol\//, "File: ")
            gsub(/,v$/, "")
            file = $0
        }
        /^revision/ {
            if (!show) {
                print file
            }
            show = 1
        }
        {
            if (show) {
                if (/^(===========)+$/) {
                    show = 0
                    print ""
                } else {
                    gsub(/;  state.*/, "")
                    if (/^(--------------)+$/) {
                        print ""
                    } else {
                        print "  ", $0
                    }
                }
            }
        }
    ' | tee /tmp/pergondiff
