////////////////////////////////////////////////////////////////////////////////////////////
//
//  Artefactdefs.inc
//
//
//    2005-07-10  -  Seppel
//
////////////////////////////////////////////////////////////////////////////////////////////

// Konstanten

Const MAGEIDOFFSET:= 100;
COnst CLERICIDOFFSET:= 200;
Const NECROIDOFFSET:= 300;

Const MINMAGEARTEFACTSCROLL:= 0xe411;
Const MAXMAGEARTEFACTSCROLL:= 0xe488;
Const MINCLERICARTEFACTSCROLL:= 0xe511;
Const MAXCLERICARTEFACTSCROLL:= 0xe588;
Const MINNECROARTEFACTSCROLL:= 0xe611;
Const MAXNECROARTEFACRSCROLL:= 0xe687;

Const MINMAGEARTEFACTID:= 111;
Const MAXMAGEARTEFACTID:= 198;
Const MINCLERICARTEFACTID:= 211;
Const MAXCLERICARTEFACTID:= 298;
Const MINNECROARTEFACTID:= 311;
Const MAXNECROARTEFACTID:= 398;

Const MINMAGEARTEFACT:= 0xe111;
Const MAXMAGEARTEFACT:= 0xe198;
Const MINCLERICARTEFACT:= 0xe211;
Const MAXCLERICARTEFACT:= 0xe298;
Const MINNECROARTEFACT:= 0xe311;
Const MAXNECROARTEFACT:= 0xe398;




